FROM onbuild:v1


#Dockerfile(dockerfile.child)
#This inherits from Dockerfile.base and triggers ONBUILD instructions.


# Extend from the base image
# FROM mybaseimage

# # Additional setup (executed after ONBUILD triggers)
# RUN echo "Child Image is now built!"
# CMD ["sleep", "200"]


# # build the base image
#docker build -t mybaseimage -f Dockerfile.base .

#build the child image

#docker build -t mychildimage -f Dockerfile.child .

# Dockerfile.base:-  Defines ONBUILD instructions but does not run them.
# Dockerfile.child:- Inherits from Dockerfile.base, triggering ONBUILD.
